

/*
 * Filename : sc_adc_type.c
 *
 * author : Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_adc_type.h"



/* USER CODE START SC_ADC_INCLUDE */
#include "adc.h"
#include "uart.h"
/* USER CODE END SC_ADC_INCLUDE */


/*
* description: Joystick Representation
* name: sc_adc
* shortname: adc
*/

/* USER CODE START SC_ADC_USERDEFINITIONS */
#define JOYSTICK_CALIBRATION_MAX        12
#define JOYSTICK_CALIBRATION_MIN       -12
/* USER CODE END SC_ADC_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_ADC signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_ADC_driverIn(SC_ADC_data_t *const data)
{
	/* USER CODE START driverInSC_ADC */

    //Temporary variable to correct the offset from Joystick
    sint8_t adcOutput_t = 0;
    
    //Read data from the MCAL driver
    if(RC_SUCCESS == ADC_getValue(&adcOutput_t))
    {
    	//Scale it to the application type
        //Software calibration for Joystick - discarding values between -12 and +12
        if(adcOutput_t > JOYSTICK_CALIBRATION_MIN && adcOutput_t < JOYSTICK_CALIBRATION_MAX)
        {
            data->adc_output = 0;
        }
        else
        {
            data->adc_output = adcOutput_t;
        }
    }
    else
    {
        UART_Log_Tx("Unable to get ADC value from Driver");
    }
    
	return RC_SUCCESS;
	/* USER CODE END driverInSC_ADC */
}
