
/*
 * Filename : sc_pwm_type.h
 *
 * author : Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SC_PWM_TYPE
#define _H_DEFINE_SC_PWM_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_PWM_INCLUDES */

/* USER CODE END SC_PWM_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_PWM signal    
 **********************************************************************/

/* USER CODE START SC_PWM_USERDEFINITIONS */

/* USER CODE END SC_PWM_USERDEFINITIONS */

typedef 
/* USER CODE START SC_PWM_SIGNALDATADEFINITION */
struct
{
	uint8_t pwm_engine;
} 
/* USER CODE END SC_PWM_SIGNALDATADEFINITION */
SC_PWM_data_t;

/* USER CODE START InitSC_PWM */
//#error "Provide a sensible init value"
#define SC_PWM_INIT_DATA ((SC_PWM_data_t){0})
/* USER CODE END InitSC_PWM */




/**
 * Default OUT driver API
 * \param const SC_PWM_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SC_PWM_driverOut(const SC_PWM_data_t  *const data);


/* USER CODE START SC_PWM_USERFUNCTIONS */

/* USER CODE END SC_PWM_USERFUNCTIONS */


#endif