

/*
 * Filename : sc_pwm_type.c
 *
 * author : Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_pwm_type.h"
#include "sp_common.h"


/* USER CODE START SC_PWM_INCLUDE */
#include "pwm_rgb.h"
/* USER CODE END SC_PWM_INCLUDE */


/*
* description: Engine data type
* name: sc_pwm
* shortname: pwm
*/

/* USER CODE START SC_PWM_USERDEFINITIONS */

/* USER CODE END SC_PWM_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_PWM signal  ****************
 *****************************************************************************************/
 
 
/**
 * Default OUT driver API
 */
inline RC_t SC_PWM_driverOut(const SC_PWM_data_t  *const data)
{
	/* USER CODE START driverOutSC_PWM */
    PWM_Green_setIntensity(data->pwm_engine);
    //PWM_Engine_WriteCompare(LED__Pulse_Width[data->pwm_engine]);
	
    //Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_PWM */
}



