
/*
 * Filename   : swc_brakelight.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SWC_BRAKELIGHT
#define _H_DEFINE_SWC_BRAKELIGHT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_BRAKELIGHT_INCLUDES */

/* USER CODE END SWC_BRAKELIGHT_INCLUDES */



/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */


/*
* component: swc_brakelight
* cycletime: 0
* description: Runnable to set the value of brakelight based on speed signal value
* events: ev_speed_onData
* name: BRAKELIGHT_setBrakelight_run
* shortname: setBrakelight
* signalIN: so_speed
* signalOUT: so_brakelight
* task: tsk_io
*/
void BRAKELIGHT_setBrakelight_run(RTE_event ev);


#endif