/*
 * Filename : swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"
#include "uart.h"

/* USER CODE START SWC_BRAKELIGHT_INCLUDE */
#include "watchdog.h"
/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */
#define BRAKELIGHT_ON                       0xFF
#define BRAKELIGHT_OFF                      0x00
#define WDG_ALIVE_STATUS_BRAKELIGHT         0x08
/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
* component: swc_brakelight
* cycletime: 0
* description: Runnable to set the value of brakelight based on speed signal value
* events: ev_speed_onData
* name: BRAKELIGHT_setBrakelight_run
* shortname: setBrakelight
* signalIN: so_speed
* signalOUT: so_brakelight
* task: tsk_io
*/
void BRAKELIGHT_setBrakelight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_setBrakelight_run */
    //Getter function for speed data
    SC_SPEED_data_t speed_t = RTE_SC_SPEED_get(&SO_SPEED_signal);
    RTE_signalStatus_t speedSignalStatus = RTE_SC_SPEED_getStatus(&SO_SPEED_signal);
    
    //Struct variable to set brakelight value
    SC_GPIO_data_t brakelight_t;
    
    //Turn brakelight ON when speed is zero
    if(RTE_SIGNALSTATUS_VALID == speedSignalStatus)
    {
        if(0 == speed_t.speed)
        {
            brakelight_t.brakeLight = BRAKELIGHT_ON;
        }
        else
        {
            brakelight_t.brakeLight = BRAKELIGHT_OFF;
        }
    }
    else
    {  
        UART_Log_Tx("Invalid speed signal received(BL)");
    }

    //Set the brakelight value to signal object and push it to the out driver
    if(RC_SUCCESS == RTE_SC_GPIO_set (&SO_BRAKELIGHT_signal, brakelight_t))
    {
        RTE_SC_GPIO_pushPort(&SO_BRAKELIGHT_signal);
    }
    else
    {
        UART_Log_Tx("Could not set brakelight signal");
    }
    
    //Report Alive Status to Watchdog timer
    WD_Alive(WDG_ALIVE_STATUS_BRAKELIGHT);
       
    /* USER CODE END BRAKELIGHT_setBrakelight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

