

/*
 * Filename : swc_joystick.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_joystick.h"
#include "uart.h"
#include "watchdog.h"


/* USER CODE START SWC_JOYSTICK_INCLUDE */
#include <stdio.h>
/* USER CODE END SWC_JOYSTICK_INCLUDE */

#include "sp_common.h"

/* USER CODE START SWC_JOYSTICK_USERDEFINITIONS */
#define WDG_ALIVE_STATUS_JOYSTICK       0x01

static char joystickString[50] = {0};
/* USER CODE END SWC_JOYSTICK_USERDEFINITIONS */



/*
* component: swc_joystick
* cycletime: 10
* description: Runnable to update the joystick signal using the API pullPort()
* events: 
* name: JOYSTICK_readJoystick_run
* shortname: readJoystick
* signalIN: 
* signalOUT: so_joystick
* task: tsk_io
*/
void JOYSTICK_readJoystick_run(RTE_event ev){
	
	/* USER CODE START JOYSTICK_readJoystick_run */
    if(RC_SUCCESS == RTE_SC_ADC_pullPort(&SO_JOYSTICK_signal))
    {
        //Convert data to string format and log the value on the terminal
        sprintf(joystickString, "%d", SO_JOYSTICK_signal.value.adc_output); 
        UART_Log_Tx(joystickString);
    }
    else
    {
        UART_Log_Tx("Could not fetch joystick data from port");
    }
    
    //Report Alive Status to Watchdog timer
    WD_Alive(WDG_ALIVE_STATUS_JOYSTICK);

    /* USER CODE END JOYSTICK_readJoystick_run */
}

/* USER CODE START SWC_JOYSTICK_FUNCTIONS */

/* USER CODE END SWC_JOYSTICK_FUNCTIONS */

